// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

import "time"

type TimeResult struct {
	value *time.Time
	err   error
}

// IsOk returns true when the result contains a non-nil result with no error
func (r TimeResult) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r TimeResult) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r TimeResult) Unwrap() time.Time {
	if r.IsErr() {
		panic("cannot unwrap TimeResult, it is an error")
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r TimeResult) UnwrapOr(v time.Time) time.Time {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r TimeResult) UnwrapOrElse(fn func(err error) time.Time) time.Time {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *TimeResult) Ok(v time.Time) {
	r.checkAbilityToSet()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *TimeResult) Err(err error) {
	r.checkAbilityToSet()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with TimeResult.IsErr() first.
func (r TimeResult) GetErr() error {
	return r.err
}

// Tup returns a tuple of (time.Time, error) with time.Time{} being returned for time.Time if there is an error
func (r TimeResult) Tup() (time.Time, error) {
	return r.UnwrapOr(time.Time{}), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, TimeResult.Err(err) will be called, otherwise TimeResult.Ok(v) will be called.
func (r *TimeResult) Set(v time.Time, err error) {
	if err != nil {
		r.Err(err)
		return
	}

	r.Ok(v)
}

func (r TimeResult) checkAbilityToSet() {
	if r.isSet() {
		panic("TimeResult is already set, cannot set again")
	}
}

func (r TimeResult) isSet() bool {
	return r.value != nil || r.err != nil
}
