// Code generated by github.com/tizz98/results; DO NOT EDIT.
package results

import (
	"context"
	"fmt"
)

type Uint16Result struct {
	value *uint16
	err   error
}

// SetNewUint16Result is a shortcut to creating a new Uint16Result and then calling .Set(v, err) on it.
func SetNewUint16Result(v uint16, err error) (result Uint16Result) {
	result.Set(v, err)
	return
}

// IsOk returns true when the result contains a non-nil result with no error
func (r Uint16Result) IsOk() bool {
	return r.err == nil
}

// IsErr returns true when the result contains a non-nil error
func (r Uint16Result) IsErr() bool {
	return r.err != nil
}

// Unwrap panics if the result contains an error, otherwise it returns the value
func (r Uint16Result) Unwrap() uint16 {
	if r.IsErr() {
		panic("cannot unwrap Uint16Result, it is an error")
	}
	return *r.value
}

// Expect panics with the specified message if the result contains an error, otherwise it returns the value
func (r Uint16Result) Expect(message string) uint16 {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", message, r.GetErr()))
	}
	return *r.value
}

// Expectf panics with the specified message if the result contains an error, otherwise it returns the value.
// This is different than Expect because if will automatically format the string with the given args.
func (r Uint16Result) Expectf(format string, args ...interface{}) uint16 {
	if r.IsErr() {
		panic(fmt.Errorf("%s: %w", fmt.Sprintf(format, args...), r.GetErr()))
	}
	return *r.value
}

// UnwrapOr returns the value if there is not an error, otherwise the specified value is returned
func (r Uint16Result) UnwrapOr(v uint16) uint16 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return v
}

// UnwrapOrElse returns the value if there is not an error, otherwise the function is called and the result is returned
func (r Uint16Result) UnwrapOrElse(fn func(err error) uint16) uint16 {
	if r.IsOk() {
		return r.Unwrap()
	}
	return fn(r.err)
}

// Ok sets the result to a successful result with the provided value.
// This will panic if the result has already been set to successful or an error.
func (r *Uint16Result) Ok(v uint16) {
	r.checkAbilityToSet()
	r.value = &v
}

// Err sets the result to an error result with the provided error.
// This will panic if the result has already been set to successful or an error.
func (r *Uint16Result) Err(err error) {
	r.checkAbilityToSet()
	r.err = err
}

// GetError returns the error of the result. It may be nil, so check with Uint16Result.IsErr() first.
func (r Uint16Result) GetErr() error {
	return r.err
}

// Tup returns a tuple of (uint16, error) with 0 being returned for uint16 if there is an error
func (r Uint16Result) Tup() (uint16, error) {
	return r.UnwrapOr(0), r.err
}

// Set is a shortcut to checking the value of an error before setting the result.
// If there is an error, Uint16Result.Err(err) will be called, otherwise Uint16Result.Ok(v) will be called.
func (r *Uint16Result) Set(v uint16, err error) {
	if err != nil {
		r.Err(err)
		return
	}

	r.Ok(v)
}

func (r Uint16Result) checkAbilityToSet() {
	if r.isSet() {
		panic("Uint16Result is already set, cannot set again")
	}
}

func (r Uint16Result) isSet() bool {
	return r.value != nil || r.err != nil
}

// ContextWithUint16 embeds the given value of uint16 into the context for later retrieval with Uint16FromContext
func ContextWithUint16(ctx context.Context, key interface{}, v uint16) context.Context {
	return context.WithValue(ctx, key, v)
}

// Uint16FromContext attempts to retrieve a uint16 value from the specified context. A Uint16Result is returned
// which can be used to inspect the success or failure of retrieval.
func Uint16FromContext(ctx context.Context, key interface{}) (result Uint16Result) {
	if v, ok := ctx.Value(key).(uint16); !ok {
		result.Err(fmt.Errorf("%#v not found in context", key))
	} else {
		result.Ok(v)
	}
	return
}
